name: my_gym_coach
description: Flutter Clean Architecture Series
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.0
  ionicons: ^0.2.2

  # Networking
  retrofit: ^3.3.0
  dio: ^4.0.6

  # State Management
  flutter_bloc: ^8.1.2

  # Others
  flutter_hooks: ^0.18.5+1
  get_it: ^7.2.0
  floor: ^1.4.1
  equatable: ^2.0.5
  oktoast: ^3.3.1
  awesome_dio_interceptor: ^0.0.2+4
  auto_route: ^5.0.4
  nb_utils: ^5.0.8
  google_fonts: ^4.0.0
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.3
  html: ^0.15.4
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  simple_animations: ^5.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.0.1
  auto_route_generator: ^5.0.3
  retrofit_generator: ^4.1.2
  floor_generator: ^1.4.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  fonts:
    - family: Butler
      fonts:
        - asset: assets/fonts/Butler_Bold.ttf
        - asset: assets/fonts/Butler_Light.ttf
        - asset: assets/fonts/Butler_Regular.ttf

    - family: IBM
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
        - asset: assets/fonts/IBMPlexSans-Light.ttf
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
  assets:
    - images/
    - images/app/
    - images/app/icons/
    - images/app/socialIcons/
    - images/learner/
    - images/theme6/